# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'capybara'
gem 'capybara-screenshot'
gem 'rspec'
gem 'rspec-expectations'
gem 'selenium-webdriver'
